version: '3'

services:
  bingo:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: "Haslo123"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "bingo"
    ports:
      - "5432:5432"
    volumes:
      - bingo-data:/var/lib/postgresql/data

volumes:
  bingo-data:
